dbt_hdb_resale:
  outputs:
    dev:
      dataset: dev_hdb_resale
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/sctp/sctp-dsai-ds3f-ds5-d1606b4d308b.json
      location: US
      method: service-account
      priority: interactive
      project: sctp-dsai-ds3f-ds5
      threads: 2
      type: bigquery
    prod:
      dataset: prod_hdb_resale
      job_execution_timeout_seconds: 300
      job_retries: 5
      keyfile: /home/sctp/sctp-dsai-ds3f-ds5-d1606b4d308b.json
      location: US
      method: service-account
      priority: interactive
      project: sctp-dsai-ds3f-ds5
      threads: 3
      type: bigquery
  target: dev